### DISCUSSION TITLE
Virtual Hosts created via API disappearing After Restart (Docker)

### DISCUSSION THREAD

**Discussion by UltimatumGamer** [OvenMediaLabs/OvenMediaEngine#1673] [Help]
Hello,

I have a question about creating VHosts using the API. I understand from a previous discussion https://github.com/AirenSoft/OvenMediaEngine/discussions/1620#discussioncomment-9490167 that separate VHosts are needed for creating apps via the api.

I'm able to successfully create a VHost via the API POST (`/v1/vhosts`), but it disappears after I restart the OvenMediaEngine container. Interestingly, scheduled channels created via the API (which generate `.sch` files) persist after restarts.

Is this the intended behavior for VHosts, or am I missing something?

**My Docker Compose Setup:**
```yml
services:
  ovenmediaengine:
    image: airensoft/ovenmediaengine:latest
    ports:
    - "8081:8081/tcp" # API
    - "9000:9000/tcp" # OVT(Origin)
    - "1935:1935/tcp" # RTMP Provider
    - "9999:9999/udp" # SRT
    - "3333:3333/tcp" # WebRTC Signaling / LLHLS
    - "3478:3478/tcp" # WebRTC TURN
    - "20080:20080/tcp" # Thumbnail
    - "10000-10004:10000-10004/udp" # WebRTC Candidate
    environment:
    - OME_HOST_IP=192.168.0.160
    - OME_ORIGIN_PORT=9000
    - OME_RTMP_PROV_PORT=1935
    - OME_SRT_PROV_PORT=9999
    - OME_LLHLS_STREAM_PORT=3333
    - OME_WEBRTC_SIGNALLING_PORT=3333
    - OME_WEBRTC_TCP_RELAY_PORT=3478
    - OME_WEBRTC_CANDIDATE_PORT=10000-10004/udp
    restart: always
    volumes:
    - ./conf:/opt/ovenmediaengine/bin/origin_conf
    - ./logs:/var/log/ovenmediaengine
    - ./media:/opt/ovenmediaengine/media
    - ./recordings:/opt/ovenmediaengine/recordings
    #- ./multiplex:/opt/ovenmediaengine/multiplex
  ovenmediaengine_demo:
    image: airensoft/ovenplayerdemo:latest
    ports:
    - "8090:80/tcp"
```
